export default {
  BACKGROUND: '#22272E',
  BACKGROUND_CATEGORY: '#162133',
  CATEGORY_TEXT: '#EFEFEF',
  HIGH_CONTENT: '#FFFFFF',
  TEXT_TITLE: '#FFFFFF',
  TEXT_CONTENT: '#EFEFEF',
  EMPTY_TEXT: '#FFFFFF',
  EMPTY_BUTTON: '#EFEFEF',
  EMPTY_BUTTON_TEXT: '#22272E',
  LINKS: '#FFFF00'
};